language: node_js
node_js:
  - "node"
services:
  - mongodb
  - postgresql
before_script:
  - sleep 15 # allows mongo to warm up
  - psql -c 'create database wrestler;' -U postgres
  - yarn pg-db-migrate up
after_success: yarn run coverage
